---

- name: 'Reload systemd'
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  become_user: 'root'

- name: 'Start Cardano node'
  ansible.builtin.service:
    name: 'cnode.service'
    state: 'started'
  become: true
  become_user: 'root'

- name: 'Start Submit Api'
  ansible.builtin.systemd:
    name: 'cnode-submit-api.service'
    state: 'started'
    become: true
    become_user: 'root'
