---

- hosts: all

  tasks:

    - name: Include cndeploy-os-tweaks
      include_role:
        name: cndeploy-os-tweaks

    - name: Include cndeploy-os-pkgs
      include_role:
        name: cndeploy-os-pkgs

    - name: Include cndeploy-os-fw
      include_role:
        name: cndeploy-os-fw

    # Activate only build or sync-bin
    #- name: Include cndeploy-cnode-build
    #  include_role:
    #    name: cndeploy-cnode-build
    - name: Include cndeploy-cnode-sync-bin
      include_role:
        name: cndeploy-cnode-sync-bin

    # TODO: Evaluate when/if it is worth to manually sync the db files from origin
    - name: Include cndeploy-cnode-sync-db
      include_role:
        name: cndeploy-cnode-sync-db

    - name: Include cndeploy-cnode-conf
      include_role:
        name: cndeploy-cnode-conf

    # TODO: Evaluate current monitoring options, disabled for now
    #- name: Include cndeploy-cnode-mon
    #  include_role:
    #    name: cndeploy-cnode-mon
