# Ansible role that sets the firewall policy.
# Actions performed:
# - Check input variables
# - Optionally disable IPv6
# - Disable ufw and firewalld
# - Setup iptables rules according to node's role from templates (idempotently).
# - Optionally setup allow-hostname script to allow connections from a ddns hostname.
#
# TODO: Testing for Redhat family
---

# Resolve var values
- name: 'Resolve platform specific vars'
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - '{{ role_path }}/vars'
      skip: true

- name: 'Resolve master IP'
  ansible.builtin.set_fact:
    master_ip: '{{ ansible_env["SSH_CLIENT"].split() | first }}'

- name: 'Show master IP (origin of current connection)'
  ansible.builtin.debug:
    msg: '{{ master_ip }}'

- name: 'Resolve SSH host IP'
  # hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]
  ansible.builtin.set_fact:
    ssh_host_ip: '{{ ansible_env["SSH_CONNECTION"].split(" ")[2] }}'

- name: 'Show SSH host IP (destination of current connection)'
  ansible.builtin.debug:
    msg: '{{ ssh_host_ip }}'

# cndeploy _node_ip _node_port _node_prio _node_type are required by this role
- name: 'Check variables: hostvars for required fields in every needed host'
  when:
    - hostvars[item]['cndeploy_node_type']|lower|default('') == 'relay' or
      hostvars[item]['cndeploy_node_type']|lower|default('') == 'bp'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> hostvars definition must contain valid values for keys
      cndeploy_node_ip
      cndeploy_node_type
      cndeploy_node_port
      cndeploy_node_prio
    quiet: true
    that:
      - (hostvars[item]['cndeploy_node_ip']|ipv4 or lookup('dig', hostvars[item]['cndeploy_node_ip']) != 'NXDOMAIN')
      - hostvars[item]['cndeploy_node_port'] is integer
      - hostvars[item]['cndeploy_node_port'] >= 1
      - hostvars[item]['cndeploy_node_port'] <= 65535
      - hostvars[item]['cndeploy_node_prio']|default(50)|int != 0
      - hostvars[item]['cndeploy_node_prio']|default(50)|int >= 1
      - hostvars[item]['cndeploy_node_prio']|default(50)|int <= 99
  with_items: '{{ groups["all"] }}'

- name: 'Check variables: cndeploy_node_type'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> Valid type values are "relay", "bp" and "standby".
    quiet: true
    that:
      - (cndeploy_node_type|default('standby')|lower == 'relay' or
         cndeploy_node_type|default('standby')|lower == 'bp' or
         cndeploy_node_type|default('standby')|lower == 'standby')

- name: 'Check variables: cndeploy_node_ip'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> cndeploy_node_ip must contain valid IPv4 addresses.
    quiet: true
    that:
      - cndeploy_node_ip|ansible.utils.ipv4

- name: 'Check variables: cndeploy_node_port'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> cndeploy_node_port must be an integer between 1 and 65535.
    quiet: true
    that:
      - cndeploy_node_port|default(3001)|int != 0
      - cndeploy_node_port|default(3001)|int >= 1
      - cndeploy_node_port|default(3001)|int <= 65535

- name: 'Check variables: cndeploy_node_prio'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> cndeploy_node_prio must be an integer between 1 and 99.
    quiet: true
    that:
      - cndeploy_node_prio|default(50)|int != 0
      - cndeploy_node_prio|default(50)|int >= 1
      - cndeploy_node_prio|default(50)|int <= 99

- name: 'Check variables: cndeploy_whitelist_ip'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> cndeploy_whitelist_ip must contain valid IPv4 addresses.
    quiet: true
    that:
      - item|ansible.utils.ipv4
  loop: '{{ cndeploy_whitelist_ip }}'
  when: cndeploy_whitelist_ip is defined

- name: 'Check variables: cndeploy_blacklist_ip'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> cndeploy_blacklist_ip must contain valid IPv4 addresses.
    quiet: true
    that:
      - item|ansible.utils.ipv4
  loop: '{{ cndeploy_blacklist_ip }}'
  when: cndeploy_blacklist_ip is defined

- name: 'Check variables: cndeploy_allowhostname'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> allowhostname must be defined and resolve to an IPv4 address.
    quiet: true
    that:
      - cndeploy_allowhostname is defined
      - (lookup("dig", cndeploy_allowhostname) != 'NXDOMAIN')
  when: cndeploy_allowhostname_enabled|default(false)|bool

# Actions
- name: 'Install dependencies for the OS'
  ansible.builtin.package:
    name: '{{ cndeploy_pkgs_dep|default([]) }}'
    state: 'present'
  become: true
  become_user: 'root'

- name: 'Disable IPv6'
  ansible.posix.sysctl: name={{ item }} value=1 state=present reload=yes
  become: yes
  become_user: 'root'
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when: cndeploy_disable_ipv6|default(false)|bool

- name: 'Setup firewall'
  # Ensure that the only firewall active is iptables as we require an idempotent
  # set of rules by flushing and loading from file at each execution.
  become: yes
  become_user: 'root'
  when: cndeploy_firewall_enabled|default(false)|bool
  block:
    - name: 'If iptables is available, proceed to setup firewalls...'
      ansible.builtin.stat:
        path: '/usr/sbin/iptables'
      register: iptables
    - name: 'Iptables is available, proceed to setup firewalls...'
      when: iptables.stat.exists
      block:
        - name: 'Disable UFW and enable netfilter-persistent'
          when: ansible_os_family == "Debian"
          block:
            - name: 'Disable UFW'
              ansible.builtin.systemd:
                name: 'ufw.service'
                state: 'stopped'
                enabled: false
              #community.general.ufw:
              #  state: 'disabled'
            - name: 'Enable netfilter-persistent'
              ansible.builtin.systemd:
                enabled: true
                name: 'netfilter-persistent.service'
                state: 'started'
        - name: 'Disable firewalld and enable iptables'
          when: ansible_os_family == "Redhat"
          block:
            - name: 'Disable firewalld'
              ansible.builtin.systemd:
                enabled: false
                masked: true
                name: 'firewalld.service'
                state: 'stopped'
            - name: 'Enable iptables'
              ansible.builtin.systemd:
                enabled: true
                name: 'iptables.service'
                state: 'started'
        - name: 'Activate Forwarding'
          ansible.posix.sysctl:
            name: 'net.ipv4.ip_forward'
            value: '1'
            sysctl_set: yes
            state: 'present'
            reload: true
        - name: 'Activate Forwarding from localhost'
          ansible.posix.sysctl:
            name: 'net.ipv4.conf.all.route_localnet'
            value: '1'
            sysctl_set: yes
            state: 'present'
            reload: true
        - name: 'Deploy iptables rules for Debian family'
          when: ansible_os_family == "Debian"
          block:
            - name: 'Deploy IP4 BP rules from template for Debian family'
              ansible.builtin.template:
                dest: '/etc/iptables/rules.v4'
                mode: '0644'
                src: 'iptables-rules-4-bp.j2'
              notify: 'Apply IP4 rules from file for Debian family'
              when: cndeploy_node_type|default('standby')|lower == 'bp'
            - name: 'Deploy IP4 Relay rules from template for Debian family'
              ansible.builtin.template:
                dest: '/etc/iptables/rules.v4'
                mode: '0644'
                src: 'iptables-rules-4-relay.j2'
              notify: 'Apply IP4 rules from file for Debian family'
              when: cndeploy_node_type|default('standby')|lower == 'relay'
            - name: 'Deploy IP4 Standby rules from template for Debian family'
              ansible.builtin.template:
                dest: '/etc/iptables/rules.v4'
                mode: '0644'
                src: 'iptables-rules-4-standby.j2'
              notify: 'Apply IP4 rules from file for Debian family'
              when: cndeploy_node_type|default('standby')|lower == 'standby'
            - name: 'Deploy IP6 rules from template for Debian family'
              ansible.builtin.template:
                dest: '/etc/iptables/rules.v6'
                mode: '0644'
                src: 'iptables-rules-6.j2'
              notify: 'Apply IP6 rules from file for Debian family'
        - name: 'Deploy iptables rules for Redhat family'
          when: ansible_os_family == "Redhat"
          block:
            - name: 'Deploy IP4 BP rules from template for Redhat family'
              ansible.builtin.template:
                dest: '/etc/sysconfig/iptables'
                mode: '0644'
                src: 'iptables-rules-4-bp.j2'
              notify: 'Apply IP4 rules from file for Redhat family'
              when: cndeploy_node_type|default('standby')|lower == 'bp'
            - name: 'Deploy IP4 Relay rules from template for Redhat family'
              ansible.builtin.template:
                dest: '/etc/sysconfig/iptables'
                mode: '0644'
                src: 'iptables-rules-4-relay.j2'
              notify: 'Apply IP4 rules from file for Redhat family'
              when: cndeploy_node_type|default('standby')|lower == 'relay'
            - name: 'Deploy IP4 Standby rules from template for Redhat family'
              ansible.builtin.template:
                dest: '/etc/sysconfig/iptables'
                mode: '0644'
                src: 'iptables-rules-4-standby.j2'
              notify: 'Apply IP4 rules from file for Redhat family'
              when: cndeploy_node_type|default('standby')|lower == 'standby'
            - name: 'Deploy IP6 rules from template for Redhat family'
              ansible.builtin.template:
                dest: '/etc/sysconfig/ip6tables'
                mode: '0644'
                src: 'iptables-rules-6.j2'
              notify: 'Apply IP6 rules from file for Redhat family'

- name: 'Setup allow-hostname in iptables mode'
  become: true
  become_user: 'root'
  when:
    - cndeploy_allowhostname_enabled|default(false)|bool
    - cndeploy_allowhostname is defined
  block:
    - name: 'Check if allow-hostname script already exists'
      # required as get_url not always behaves like described in its documentation,
      # overwriting the file when it exists, even with force:no and dest being the full file path
      ansible.builtin.stat:
        get_checksum: false
        get_md5: false
        path: '/usr/local/bin/allow-hostname.bash'
      changed_when: false
      register: allowhostname_file_check
    - name: 'Download allow-hostname script'
      ansible.builtin.get_url:
        dest: '/usr/local/bin/allow-hostname.bash'
        force: false
        mode: '0700'
        url: 'https://raw.githubusercontent.com/jmhoms/allow-hostname/master/allow-hostname.bash'
      when: not allowhostname_file_check.stat.exists
    - name: 'Configure defined hostname in the script'
      ansible.builtin.lineinfile:
        dest: '/usr/local/bin/allow-hostname.bash'
        line: 'HOSTNAME={{ cndeploy_allowhostname }}'
        regexp: '^HOSTNAME='
        state: 'present'
    - name: 'Configure iptables mode in the script'
      ansible.builtin.lineinfile:
        dest: '/usr/local/bin/allow-hostname.bash'
        line: 'IPTMODE=yes'
        regexp: '^IPTMODE='
        state: 'present'
    - name: 'Configure cron to run the script every 5 minutes'
      ansible.builtin.copy:
        content: |
          */5 * * * * root /usr/local/bin/allow-hostname.bash 2>&1 | logger -t allow-hostname
        dest: '/etc/cron.d/allow-hostname'
        group: 'root'
        mode: '0644'
        owner: 'root'
