---

- name: 'Reload systemd'
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  become_user: 'root'

- name: 'Start Cardano node'
  ansible.builtin.service:
    name: 'cnode.service'
    state: 'started'
  become: true
  become_user: 'root'

- name: 'Start Cardano node in origin'
  ansible.builtin.service:
    name: 'cnode.service'
    state: 'started'
  become: true
  become_user: 'root'
  delegate_to: '{{ cndeploy_cnode_origin_host }}'

- name: 'Disallow origin public key in remote'
  ansible.posix.authorized_key:
    key: '{{ originpubkey.stdout }}'
    state: 'absent'
    user: '{{ cndeploy_user }}'

- name: 'Disallow connections on port 22 from origin using iptables'
  ansible.builtin.iptables:
    chain: 'INPUT'
    protocol: 'tcp'
    source: '{{ cndeploy_cnode_origin_host }}'
    destination_ports: '22'
    jump: 'ACCEPT'
    state: 'absent'
  become: yes
  become_user: 'root'
