# Ansible role containing tasks to build and install Guild's operator cnode.
# TODO: allow cnode to be installed in a custom path instead of the default one
# TODO: after install clean up

---

- name: 'Resolve platform specific vars'
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - '{{ role_path }}/vars'
      skip: true

- name: 'Resolve SSH host IP'
  ansible.builtin.set_fact:
    ssh_host_ip: '{{ ansible_env["SSH_CONNECTION"].split(" ")[2] }}'

- name: 'Resolve node definition vars if present'
  when: cndeploy_nodes is defined
  block:
    - name: 'Export the dictionary containing this node variables to cndeploy_node'
      ansible.builtin.set_fact:
        cndeploy_node: '{{ item }}'
      with_list: '{{ cndeploy_nodes }}'
      when: item.cndeploy_node_management_ip == ssh_host_ip
    - name: 'Resolve the variables contained in cndeploy_node'
      when: cndeploy_node is defined
      ansible.builtin.set_fact:
        '{{ item.key }}': '{{ item.value }}'
      with_dict: '{{ cndeploy_node }}'

- name: 'Resolve cndeploy_nodes_types.all dictionary vars if present'
  when: cndeploy_nodes_types.all is defined
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_nodes_types.all }}'

- name: 'Resolve cndeploy_nodes_types.{{ cndeploy_node_type }} dictionary vars if present'
  when: 'cndeploy_nodes_types[cndeploy_node_type] is defined'
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_nodes_types[cndeploy_node_type] }}'

- name: 'Resolve cndeploy_nodes_types.{{ cndeploy_node_management_ip }} dictionary vars if present'
  when: 'cndeploy_nodes_types[cndeploy_node_management_ip] is defined'
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_nodes_types[cndeploy_node_management_ip] }}'

- name: 'Install dependencies for the OS'
  ansible.builtin.package:
    name: '{{ cndeploy_pkgs_dep|default([]) }}'
    state: 'present'
  become: true
  become_user: 'root'

- name: 'Stop the node service if it exists and it is started'
  ansible.builtin.service:
    name: 'cnode.service'
    state: 'stopped'
  become: true
  become_user: 'root'
  failed_when: cnodeservice is failed and not 'Could not find the requested service' in cnodeservice.msg
  notify: 'Start Cardano node'
  register: cnodeservice

- name: 'Install Guild Operators CNODE'
  block:
    - name: 'Ensures $HOME/tmp exist'
      ansible.builtin.file:
        path: '~/tmp'
        recurse: true
        state: 'directory'
    - name: 'Get Guild Operators prereqs.sh script'
      ansible.builtin.get_url:
        dest: '~/tmp/'
        mode: '0755'
        url: 'https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh'
    - name: 'Run prereqs.sh installer without Rust and cncli'
      ansible.builtin.command:
        cmd: '~/tmp/prereqs.sh -f'
      when: not cndeploy_cnode_cncli_install
    - name: 'Run prereqs.sh installer with Rust and cncli'
      ansible.builtin.command:
        cmd: '~/tmp/prereqs.sh -f -c'
      when: cndeploy_cnode_cncli_install
    - name: 'Run git clone'
      ansible.builtin.command:
        chdir: '~/git'
        cmd: 'git clone https://github.com/input-output-hk/cardano-node'
        creates: '~/git/cardano-node'
    #- name: 'Run git fetch'
    #  ansible.builtin.command:
    #    chdir: '~/git/cardano-node'
    #    cmd: 'git fetch --tags --all'
    #- name: 'Run git pull'
    #  ansible.builtin.command:
    #    chdir: '~/git/cardano-node'
    #    cmd: 'git pull origin master'
    #- name: 'Run git checkout'
    #  ansible.builtin.shell:
    #    chdir: '~/git/cardano-node'
    #    cmd: 'git checkout $(curl -s https://api.github.com/repos/input-output-hk/cardano-node/releases/latest | jq -r .tag_name)'
    #- name: 'Run cabal-build-all.sh'
    #  ansible.builtin.command:
    #    chdir: '~/git/cardano-node'
    #    cmd: '{{ cndeploy_cnode_dir }}/scripts/cabal-build-all.sh'
    - name: 'Get and build Cardano node'
      ansible.builtin.shell:
        cmd: |
          cd ~/git/cardano-node
          source ~/.bashrc && git fetch --tags --all
          source ~/.bashrc && git pull origin master
          source ~/.bashrc && git checkout $(curl -s https://api.github.com/repos/input-output-hk/cardano-node/releases/latest | jq -r .tag_name)
          source ~/.bashrc && echo $PATH
          source ~/.bashrc && {{ cndeploy_cnode_dir }}/scripts/cabal-build-all.sh
      args:
        executable: /bin/bash
      register: cnodebuild
    - name: 'Debug Cardano Node'
      ansible.builtin.debug:
        msg: '{{ cnodebuild.stdout }}'
