# Ansible role that prepares the OS before installing the cardano node
# For now it can:
# - Change the hostname
# - Add hosts
# - Enforce secure options for the SSH service
# - Setup swap

---

- name: 'Resolve platform specific vars'
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - '{{ role_path }}/vars'
      skip: true

- name: 'Check variables: cndeploy_node_hostname'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> hostname must be a string formed by up to 253 characters,
      (a to z, A to Z, 0 to 9, _, -, .)
    quiet: true
    that:
      - cndeploy_node_hostname is defined
      - cndeploy_node_hostname is match('^[a-zA-Z0-9-_.]{1,253}$')
  when: cndeploy_node_hostname_change|default(false)|bool

- name: 'Check variables: cndeploy_swap_file_size_mb'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> swap_file_size_mb must be an integer greater than 1.
    quiet: true
    that:
      - cndeploy_swap_file_size_mb|int is integer
      - cndeploy_swap_file_size_mb|int >= 1
  when:
    - cndeploy_swap_configure|default(false)|bool
    - cndeploy_swap_enable|default(false)|bool

- name: 'Check variables: cndeploy_swappiness'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> swappiness must be a number between 0 and 100.
    quiet: true
    that:
      - cndeploy_swappiness|int is integer
      - cndeploy_swappiness|int >= 0
      - cndeploy_swappiness|int <= 100
  when:
    - cndeploy_swap_configure|default(false)|bool
    - cndeploy_swap_enable|default(false)|bool

- name: 'Install dependencies for the OS'
  ansible.builtin.package:
    name: '{{ cndeploy_pkgs_dep|default([]) }}'
    state: 'present'
  become: true
  become_user: 'root'

- name: 'Set hostname'
  ansible.builtin.hostname:
    name: '{{ cndeploy_node_hostname }}'
  become: true
  become_user: 'root'
  when:
    - cndeploy_node_hostname_change|default(false)|bool
    - cndeploy_node_hostname is defined

- name: 'Add entries to hosts file'
  ansible.builtin.blockinfile:
    path: '/etc/hosts'
    block: '{{ cndeploy_hosts }}'
  become: true
  become_user: 'root'
  when:
    - cndeploy_hosts_change|default(false)|bool
    - cndeploy_hosts is defined

- name: 'Secure SSH access if not connected as root'
  ansible.builtin.copy:
    dest: '/etc/ssh/sshd_config.d/05-ssh-secured.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    content: |
      PermitRootLogin prohibit-password
      PubkeyAuthentication yes
      PasswordAuthentication no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      UsePAM yes
      X11Forwarding yes
  become: true
  become_user: 'root'
  notify: 'Restart SSH service'
  when:
    - cndeploy_ssh_restrict|default(false)|bool
    - ansible_user_id != 'root'

- name: 'Setup an additional Swap file'
  # based on Greg Dubicki's code
  become: true
  become_user: 'root'
  when: cndeploy_swap_configure|default(false)|bool
  block:
    - name: 'Check if swap file exists'
      ansible.builtin.stat:
        get_checksum: false
        get_md5: false
        path: '{{ cndeploy_swap_file_path }}'
      changed_when: false
      register: swap_file_check
    - name: 'Set variable for existing swap file size'
      ansible.builtin.set_fact:
        swap_file_existing_size_mb: '{{ (swap_file_check.stat.size / 1024 / 1024) | int }}'
      when: swap_file_check.stat.exists
    - name: 'Show calculated value for swap_file_existing_size_mb'
      ansible.builtin.debug:
        msg: '{{ swap_file_existing_size_mb }}'
      when: swap_file_check.stat.exists
    - name: 'Check if swap is on'
      ansible.builtin.shell:
        cmd: 'swapon --show | grep {{ cndeploy_swap_file_path|quote }}'
      changed_when: false
      check_mode: false
      failed_when: false
      register: swap_is_enabled
    - name: 'Disable swap'
      ansible.builtin.command:
        cmd: 'swapoff {{ cndeploy_swap_file_path|quote }}'
      register: swap_disabled
      when: >
        swap_file_check.stat.exists
        and 'rc' in swap_is_enabled and swap_is_enabled.rc == 0
        and (not cndeploy_swap_enable|default(false)|bool
             or (cndeploy_swap_enable|default(false)|bool
                 and swap_file_existing_size_mb|int != cndeploy_swap_file_size_mb|int
                )
            )
    - name: 'Delete the swap file'
      ansible.builtin.file:
        path: '{{ cndeploy_swap_file_path }}'
        state: 'absent'
      when: not cndeploy_swap_enable|default(false)|bool
    - name: 'Remove swap entry from fstab'
      ansible.posix.mount:
        dump: '0'
        fstype: 'swap'
        name: 'none'
        opts: 'sw'
        passno: '0'
        src: '{{ cndeploy_swap_file_path }}'
        state: 'absent'
      when: not cndeploy_swap_enable|default(false)|bool
    - name: 'Configure swap'
      when: cndeploy_swap_enable|default(false)|bool
      block:
        - name: 'Create or change the size of swap file'
          ansible.builtin.command:
            cmd: 'dd if=/dev/zero of={{ cndeploy_swap_file_path|quote }} count={{ cndeploy_swap_file_size_mb|quote }} bs=1MiB'
          register: swap_file_created
          when: >
            not swap_file_check.stat.exists
            or swap_file_existing_size_mb|int != cndeploy_swap_file_size_mb|int
        - name: 'Change swap file permissions'
          ansible.builtin.file:
            mode: '0600'
            path: '{{ cndeploy_swap_file_path }}'
        - name: 'Check if swap is formatted'
          ansible.builtin.shell:
            cmd: 'file {{ cndeploy_swap_file_path|quote }} | grep "swap file"'
          changed_when: false
          check_mode: false
          failed_when: false
          register: swap_file_is_formatted
        - name: 'Format swap file if it is not formatted'
          ansible.builtin.command:
            cmd: 'mkswap {{ cndeploy_swap_file_path|quote }}'
          when: >
            ('rc' in swap_file_is_formatted and swap_file_is_formatted.rc > 0)
            or swap_file_created.changed
        - name: 'Add swap entry to fstab'
          ansible.posix.mount:
            dump: '0'
            fstype: 'swap'
            name: 'none'
            opts: 'sw'
            passno: '0'
            src: '{{ cndeploy_swap_file_path }}'
            state: 'present'
        - name: 'Turn on swap'
          ansible.builtin.shell:
            cmd: 'swapon -a'
          # if swap was disabled from the start
          # or has been disabled to change its params
          when: >
            ('rc' in swap_is_enabled and swap_is_enabled.rc != 0)
            or swap_disabled.changed
        - name: 'Configure swappiness'
          ansible.posix.sysctl:
            name: 'vm.swappiness'
            state: 'present'
            value: '{{ cndeploy_swappiness|string }}'
