# Ansible role that expects a root connection to the host, in order to
# create an admin user (with sudo privileges), that can be used afterwards
# by other roles to connect to the host using a pubkey.

---

- name: 'Resolve platform specific vars'
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - '{{ role_path }}/vars'
      skip: true

- name: 'Resolve SSH host IP'
  ansible.builtin.set_fact:
    ssh_host_ip: '{{ ansible_env["SSH_CONNECTION"].split(" ")[2] }}'

- name: 'Resolve node definition vars if present'
  when: cndeploy_nodes is defined
  block:
    - name: 'Export the dictionary containing this node variables to cndeploy_node'
      ansible.builtin.set_fact:
        cndeploy_node: '{{ item }}'
      with_list: '{{ cndeploy_nodes }}'
      when: item.cndeploy_node_management_ip == ssh_host_ip
    - name: 'Resolve the variables contained in cndeploy_node'
      when: cndeploy_node is defined
      ansible.builtin.set_fact:
        '{{ item.key }}': '{{ item.value }}'
      with_dict: '{{ cndeploy_node }}'

- name: 'Resolve cndeploy_nodes_types.all dictionary vars if present'
  when: cndeploy_nodes_types.all is defined
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_nodes_types.all }}'

- name: 'Resolve cndeploy_nodes_types.{{ cndeploy_node_type }} dictionary vars if present'
  when: 'cndeploy_nodes_types[cndeploy_node_type] is defined'
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_nodes_types[cndeploy_node_type] }}'

- name: 'Resolve cndeploy_nodes_types.{{ cndeploy_node_management_ip }} dictionary vars if present'
  when: 'cndeploy_nodes_types[cndeploy_node_management_ip] is defined'
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_nodes_types[cndeploy_node_management_ip] }}'

- name: 'Create group for admin user'
  ansible.builtin.group:
    name: '{{ cndeploy_user|default(cndeploy_user_default) }}'
    state: present

- name: 'Create admin user'
  ansible.builtin.user:
    append: true
    group: '{{ cndeploy_user|default(cndeploy_user_default) }}'
    groups: '{{ cndeploy_admin_groups|default(cndeploy_admin_groups_default) }}'
    home: '{{ cndeploy_user_home|default(cndeploy_user_home_default) }}'
    name: '{{ cndeploy_user|default(cndeploy_user_default) }}'
    shell: '/bin/bash'
  become: true
  become_user: 'root'

- name: 'Allow sudo without password'
  ansible.builtin.copy:
    content: '{{ cndeploy_user|default(cndeploy_user_default) }} ALL=(ALL) NOPASSWD:ALL'
    dest: '/etc/sudoers.d/{{ cndeploy_user|default(cndeploy_user_default) }}_nopasswd'
    mode: '0440'
  become: true
  become_user: 'root'

- name: 'Set up authorized keys from public_keys directory'
  ansible.posix.authorized_key:
    key: '{{ lookup("file", item) }}'
    state: 'present'
    user: '{{ cndeploy_user|default(cndeploy_user_default) }}'
  with_fileglob: 'public_keys/*.pub'
  become: true
  become_user: 'root'

- name: 'Set up authorized keys from a list of keys'
  ansible.posix.authorized_key:
    key: '{{ item }}'
    state: 'present'
    user: '{{ cndeploy_user|default(cndeploy_user_default) }}'
  with_items: '{{ cndeploy_ssh_pubkeys|default([]) }}'
  become: true
  become_user: 'root'
  when:
    - item|length > 10
