---

- name: 'Restart SSH service'
  ansible.builtin.service:
    name: 'ssh'
    state: 'restarted'
  become: true
  become_user: 'root'

- name: 'Restart Cardano node'
  become: true
  become_user: 'root'
  block:
    - name: 'Stop Cardano node'
      ansible.builtin.command:
        cmd: 'systemctl stop cnode.service'
    - name: 'Start Cardano node'
      ansible.builtin.command:
        cmd: 'systemctl start cnode.service'
