---

- name: 'Restart SSH service'
  ansible.builtin.service:
    name: 'ssh'
    state: 'restarted'
  become: true
  become_user: 'root'

- name: 'Restart Cardano node'
  become: true
  become_user: 'root'
  block:
    - name: 'Stop Cardano node'
      ansible.builtin.service:
        name: 'cnode.service'
        state: 'stopped'
    - name: 'Wait 30 seconds to make sure the service is stopped'
      ansible.builtin.pause:
        seconds: 30
    - name: 'Start Cardano node'
      ansible.builtin.service:
        name: 'cnode.service'
        state: 'started'
