# Set the install directory, by default /opt/cardano/cnode
# IMPORTANT, for now this default path is hardcoded in some places,
# so don't change this value.
cndeploy_cnode_dir: '/opt/cardano/cnode'

# Set to true to install cncli
cndeploy_cnode_cncli_install: false
