---

- name: 'Start Cardano node'
  ansible.builtin.service:
    name: 'cnode.service'
    state: 'started'
  become: true
  become_user: 'root'

- name: 'Restart Cardano node'
  ansible.builtin.service:
    name: 'cnode.service'
    state: 'restarted'
  become: true
  become_user: 'root'
