# set to the user to be used for installation, it'll be created if don't exist
# set to '{{ ansible_user_id }}' to use the user that Ansible connects with
cndeploy_user: '{{ ansible_user_id }}'
# set to the desired/existent home for the user, init scripts will be placed
cndeploy_user_home: '/home/{{ cndeploy_user }}'
# set the install directory
cndeploy_cnode_dir: '/opt/cardano/cnode'
# Set to yes to add the defined aliases to user's bash
cndeploy_add_aliases: yes
# Define the aliases to be added
cndeploy_aliases: |
  alias g='/opt/cardano/cnode/scripts/gLiveView.sh'
  alias nstart='sudo systemctl start cnode.service'
  alias nstop='sudo systemctl stop cnode.service'
  alias nstatus='sudo systemctl status cnode.service'
  alias nlog='sudo journalctl -f -u cnode.service'
