---

- hosts: all

  tasks:

#    - name: Include cndeploy-os-tweaks
#      include_role:
#        name: cndeploy-os-tweaks

#    - name: Include cndeploy-os-pkgs
#      include_role:
#        name: cndeploy-os-pkgs

#    - name: Include cndeploy-cnode
#      include_role:
#        name: cndeploy-cnode

    - name: Include cndeploy-cardano-node
      include_role:
        name: cndeploy-cardano-node

#    - name: Include cndeploy-monitoring
#      include_role:
#        name: cndeploy-monitoring
