---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Resolve other vars
  ansible.builtin.set_fact:
    master_ip: '{{ ansible_env["SSH_CLIENT"].split() | first }}'

- name: Show Master IP (origin of current connection)
  ansible.builtin.debug:
    msg: {{ master_ip }}

- name: Install dependencies for the OS
  become: yes
  become_user: root
  ansible.builtin.package:
    name: '{{ cndeploy_pkgs_dep|default([]) }}'
    state: present

- name: Set hostname
  when:
    - cndeploy_hostname_change
    - cndeploy_hostname is defined
  become: yes
  become_user: root
  ansible.builtin.hostname:
    name: '{{ cndeploy_hostname }}'

- name: Add entries to hosts file
  when:
    - cndeploy_hosts_change
    - cndeploy_hosts is defined
  become: yes
  become_user: root
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: '{{ cndeploy_hosts }}'

- name: Secure SSH access if not connected as root
  when:
    - cndeploy_ssh_restrict
    - ansible_user_id != "root"
  become: yes
  become_user: root
  ansible.builtin.copy:
    dest: '/etc/ssh/sshd_config.d/05-ssh-secured.conf'
    owner: root
    group: root
    mode: 0644
    content: |
      PermitRootLogin prohibit-password
      PubkeyAuthentication yes
      PasswordAuthentication no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      UsePAM yes
      X11Forwarding yes
  notify: Restart SSH service

- name: Setup firewall
  when: cndeploy_firewall_enabled
  become: yes
  become_user: root
  block:
    - name: Check if ufw is available
      ansible.builtin.stat:
        path: /usr/sbin/ufw
      register: ufw
    - name: Check if firewalld is available
      ansible.builtin.stat:
        path: /usr/sbin/firewalld
      register: firewalld
    - name: Check if iptables is available
      ansible.builtin.stat:
        path: /usr/sbin/iptables
      register: iptables
    - name: Use ufw if available
      when: ufw.stat.exists
      block:
        - name: Allow SSH from defined management hosts
          community.general.ufw:
            rule: allow
            port: 22
            proto: tcp
            src: "{{ item }}"
          with_items: '{{ cndeploy_management_ip }}'
        - name: Allow everywhere access to Relay-Node port
          when: cndeploy_node_type == 'relay'
          community.general.ufw:
            rule: allow
            port: '{{ cndeploy_node_port }}'
            proto: tcp
        - name: Allow relay nodes access to BP-Node port
          when: cndeploy_node_type == 'bp'
          community.general.ufw:
            rule: allow
            port: '{{ cndeploy_node_port }}'
            proto: tcp
            src: '{{ item }}'
          with_items: '{{ cndeploy_relay_nodes_ip }}'
        - name: Enable UFW with deny as default policy
          community.general.ufw:
            state: "enabled"
            policy: "deny"
            logging: "on"
    - name: Use firewald if available when ufw is not
      # TODO testing needed
      when:
        - not ufw.stat.exists
        - firewalld.stat.exists
      block:
        - name: Allow SSH from defined management hosts
          ansible.posix.firewalld:
            permanent: yes
            state: enabled
            port: 22/tcp
            source: "{{ item }}"
          with_items: '{{ cndeploy_management_ip }}'
        - name: Allow everywhere access to Relay-Node port
          when: cndeploy_node_type == 'relay'
          ansible.posix.firewalld:
            permanent: yes
            state: enabled
            port: '{{ cndeploy_node_port }}/tcp'
        - name: Allow relay nodes access to BP-Node port
          when: cndeploy_node_type == 'bp'
          ansible.posix.firewalld:
            permanent: yes
            state: enabled
            port: '{{ cndeploy_node_port }}/tcp'
            source: '{{ item }}'
          with_items: '{{ cndeploy_relay_nodes_ip }}'
    - name: Use iptables if available when ufw and firewalld are not
      when:
        - not ufw.stat.exists
        - not firewalld.stat.exists
        - iptables.stat.exists
      # TODO finish block with iptables module + permanent changes

- name: Setup allow-hostname (Ubuntu/Debian only atm)
  when:
    - cndeploy_allowhostname_enabled
    - cndeploy_allowhostname is defined
    - ansible_facts['os_family'] == "Debian"
  become: yes
  become_user: root
  block:
    - name: Download allow-hostname script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/jmhoms/allow-hostname/master/allow-hostname.bash
        dest: /usr/local/bin/
        mode: '0700'
    - name: Configure defined hostname in the script
      ansible.builtin.lineinfile:
        dest: /usr/local/bin/allow-hostname.bash
        state: present
        regexp: '^HOSTNAME='
        line: 'HOSTNAME={{ cndeploy_allowhostname }}'
    - name: Configure ufw mode in the script
      ansible.builtin.lineinfile:
        dest: /usr/local/bin/allow-hostname.bash
        state: present
        regexp: '^UFWMODE='
        line: 'UFWMODE=yes'
    - name: Configure cron to run the script every 5 minutes
      ansible.builtin.copy:
        dest: '/etc/cron.d/allow-hostname'
        owner: root
        group: root
        mode: 0644
        content: |
          */5 * * * * root /usr/local/bin/allow-hostname.bash

- name: Setup an additional Swap file
  # based on Greg Dubicki's code
  when: cndeploy_swap_configure
  become: yes
  become_user: root
  block:
    - name: Check if swap file exists
      ansible.builtin.stat:
        path: "{{cndeploy_swap_file_path}}"
        get_checksum: false
        get_md5: false
      register: swap_file_check
      changed_when: false
    - name: Set variable for existing swap file size
      ansible.builtin.set_fact:
        swap_file_existing_size_mb: "{{ (swap_file_check.stat.size / 1024 / 1024) | int }}"
      when: swap_file_check.stat.exists
    - name: Check if swap is on
      ansible.builtin.shell: swapon --show | grep {{cndeploy_swap_file_path}}
      register: swap_is_enabled
      changed_when: false
      failed_when: false
    - name: Disable swap
      ansible.builtin.command: swapoff {{cndeploy_swap_file_path}}
      register: swap_disabled
      when: >
        swap_file_check.stat.exists
        and 'rc' in swap_is_enabled and swap_is_enabled.rc == 0
        and (not cndeploy_swap_enable or (cndeploy_swap_enable and swap_file_existing_size_mb != cndeploy_swap_file_size_mb))
    - name: Delete the swap file
      ansible.builtin.file:
        path: "{{cndeploy_swap_file_path}}"
        state: absent
      when: not cndeploy_swap_enable
    - name: Remove swap entry from fstab
      ansible.posix.mount:
        name: none
        src: "{{cndeploy_swap_file_path}}"
        fstype: swap
        opts: sw
        passno: '0'
        dump: '0'
        state: absent
      when: not cndeploy_swap_enable
    - name: Configure swap
      when: cndeploy_swap_enable | bool
      block:
        - name: Create or change the size of swap file
          ansible.builtin.command: dd if=/dev/zero of={{cndeploy_swap_file_path}} count={{cndeploy_swap_file_size_mb}} bs=1MiB
          register: swap_file_created
          when: >
            not swap_file_check.stat.exists
            or swap_file_existing_size_mb != cndeploy_swap_file_size_mb
        - name: Change swap file permissions
          ansible.builtin.file:
            path: "{{cndeploy_swap_file_path}}"
            mode: 0600
        - name: Check if swap is formatted
          ansible.builtin.shell: file {{cndeploy_swap_file_path}} | grep 'swap file'
          register: swap_file_is_formatted
          changed_when: false
          failed_when: false
        - name: Format swap file if it's not formatted
          ansible.builtin.command: mkswap {{cndeploy_swap_file_path}}
          when: >
            ('rc' in swap_file_is_formatted and swap_file_is_formatted.rc > 0)
            or swap_file_created.changed
        - name: Add swap entry to fstab
          ansible.posix.mount:
            name: none
            src: "{{cndeploy_swap_file_path}}"
            fstype: swap
            opts: sw
            passno: '0'
            dump: '0'
            state: present
        - name: Turn on swap
          ansible.builtin.shell: swapon -a
          # if swap was disabled from the start
          # or has been disabled to change its params
          when: >
            ('rc' in swap_is_enabled and swap_is_enabled.rc != 0)
            or swap_disabled.changed
        - name: Configure swappiness
          ansible.posix.sysctl:
            name: vm.swappiness
            value: "{{ cndeploy_swappiness|string }}"
            state: present
