# Ansible role containing tasks to synchronize the Cardano node db
# from an origin host.

---

- name: 'Resolve platform specific vars'
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - '{{ role_path }}/vars'
      skip: true

- name: 'Resolve SSH host IP'
  ansible.builtin.set_fact:
    ssh_host_ip: '{{ ansible_env["SSH_CONNECTION"].split(" ")[2] }}'

- name: 'Resolve node definition vars if present'
  when: cndeploy_nodes is defined
  block:
    - name: 'Export the dictionary containing this node variables to cndeploy_node'
      ansible.builtin.set_fact:
        cndeploy_node: '{{ item }}'
      with_list: '{{ cndeploy_nodes }}'
      when: item.cndeploy_node_management_ip == ssh_host_ip
    - name: 'Resolve the variables contained in cndeploy_node'
      when: cndeploy_node is defined
      ansible.builtin.set_fact:
        '{{ item.key }}': '{{ item.value }}'
      with_dict: '{{ cndeploy_node }}'

- name: 'Resolve cndeploy_config.all dictionary vars if present'
  when: cndeploy_config.all is defined
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_config.all }}'

- name: 'Resolve cndeploy_config.{{ cndeploy_node_type }} dictionary vars if present'
  when: 'cndeploy_config[cndeploy_node_type] is defined'
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_config[cndeploy_node_type] }}'

- name: 'Resolve cndeploy_config.{{ cndeploy_node_management_ip }} dictionary vars if present'
  when: 'cndeploy_config[cndeploy_node_management_ip] is defined'
  ansible.builtin.set_fact:
    '{{ item.key }}': '{{ item.value }}'
  with_dict: '{{ cndeploy_config[cndeploy_node_management_ip] }}'

- name: 'Check variables: cndeploy_cnode_origin_dir'
  ansible.builtin.assert:
    fail_msg: >
      Invalid value -> Local cnode directory must be also defined
      in CNODE_HOME environment variable.
    quiet: true
    that:
      - cndeploy_cnode_origin_dir == lookup('env', 'CNODE_HOME')
        or cndeploy_cnode_origin_dir_check_override
  delegate_to: '{{ cndeploy_cnode_origin_host }}'

- name: 'Install dependencies for the OS'
  ansible.builtin.package:
    name: '{{ cndeploy_pkgs_dep|default([]) }}'
    state: 'present'
  become: true
  become_user: 'root'

- name: 'Synchronize the blocks database if needed'
  block:
    - name: 'Calculate the size of the db directory in origin'
      ansible.builtin.command: '/usr/bin/du -sk {{ cndeploy_cnode_origin_dir|quote }}/db'
      become: true
      become_user: 'root'
      changed_when: false
      check_mode: false
      delegate_to: '{{ cndeploy_cnode_origin_host }}'
      register: origindbdir
    - name: 'Calculate the size of the db directory'
      ansible.builtin.command: '/usr/bin/du -sk {{ cndeploy_cnode_dir|quote }}/db'
      become: true
      become_user: 'root'
      changed_when: false
      check_mode: false
      register: dbdir
    - name: 'If db directory in remote is smaller synchronize the files'
      when: dbdir.stdout.split()[0]|int < origindbdir.stdout.split()[0]|int
      block:
        - name: 'Stop the service in origin'
          ansible.builtin.service:
            name: 'cnode.service'
            state: 'stopped'
          become: true
          become_user: 'root'
          delegate_to: '{{ cndeploy_cnode_origin_host }}'
          notify: 'Start Cardano node in origin'
          register: originservice
        - name: 'Wait 30 seconds to make sure the service in origin is stopped'
          ansible.builtin.pause:
            seconds: 30
          when: originservice.changed
        - name: 'Stop the remote service if needed'
          ansible.builtin.service:
            name: 'cnode.service'
            state: 'stopped'
          become: true
          become_user: 'root'
          notify: 'Start Cardano node'
          register: remoteservice
        - name: 'Wait 30 seconds to make sure the remote service is stopped'
          ansible.builtin.pause:
            seconds: 30
          when: remoteservice.changed
        - name: 'Temporarily allow ssh from non-master origin to remote'
          become: yes
          become_user: 'root'
          when:
            - cndeploy_firewall_enabled|default(false)|bool
            - cndeploy_cnode_origin_host != 'localhost'
            - cndeploy_cnode_origin_host != '127.0.0.1'
          block:
            - name: 'Check if iptables is available'
              ansible.builtin.stat:
                path: '/usr/sbin/iptables'
              register: iptables
            - name: 'Allow connections on port 22 from origin using iptables'
              ansible.builtin.iptables:
                chain: 'INPUT'
                protocol: 'tcp'
                source: '{{ cndeploy_cnode_origin_host }}'
                destination_ports: '22'
                jump: 'ACCEPT'
              notify: 'Disallow connections on port 22 from origin using iptables'
              when:
                - iptables.stat.exists
        - name: 'Create a keypair in origin if it does not already exist'
          ansible.builtin.command:
            cmd: 'ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa'
            creates: '~/.ssh/id_rsa.pub'
          delegate_to: '{{ cndeploy_cnode_origin_host }}'
        - name: 'Get the pub key into a variable'
          ansible.builtin.command: '/usr/bin/cat ~/.ssh/id_rsa.pub'
          changed_when: false
          check_mode: false
          delegate_to: '{{ cndeploy_cnode_origin_host }}'
          register: originpubkey
        - name: 'Temporarily allow origin public key in remote if not already allowed'
          ansible.posix.authorized_key:
            key: '{{ originpubkey.stdout }}'
            state: 'present'
            user: '{{ cndeploy_user }}'
          notify: 'Disallow origin public key in remote'
        - name: 'Copy the database from origin to remote node'
          ansible.posix.synchronize:
            archive: true
            delete: true
            dest: '{{ cndeploy_cnode_dir }}/'
            mode: 'push'
            src: '{{ cndeploy_cnode_origin_dir }}/db'
          delegate_to: '{{ cndeploy_cnode_origin_host }}'
